### ISSUE TITLE
Runner configuration save 

### ISSUE THREAD

**Issue by Chomikmarkus** [adeadfed/myaso#2]
Getting error when run bake command! 
TypeError: unsupported operand type(s) for |=: 'dict' and 'd
ict'

 
 
 
![Screenshot_20211206-110637](https://user-images.githubusercontent.com/92059377/144818182-c24648f0-222d-4b6e-9c3e-6de327acfbae.png)

**Comment by harpsiford** [comment]
Hello @Chomikmarkus! 
Please provide the output of the following commands: `python3 -V`, `python -V`. The tool should work without problems on Python 3.9+. 

We will update the README to include the minimal Python version, and make the tool more compatible if there are issues with Python 3.9/3.8+ depending on the situation. 

It will also be helpful to see the full stack trace, if there is anything left out of the screenshot. 

In the meantime, you can try the Docker version to achieve the results without waiting for the fix.

**Comment by Chomikmarkus** [comment]
root@vps158041:~/PEzor# python3 -V
Python 3.8.10
root@vps158041:~/PEzor# python2 -V
Python 2.7.18
root@vps158041:~/PEzor#

**Comment by harpsiford** [comment]
Glad the problem is resolved for you! 

Will look into Python 3.8.x compatibility. Can’t promise anything, but if the changes are not too large, myaso will support it. If not, we’ll update the README with compatibility info anyway.

**Comment by Chomikmarkus** [comment]
Docker version suits well for me as well!
